name: Android Pull Request to Release

on:
  pull_request:
    branches:
      - release-[0-9]+.[0-9]+.[0-9]+

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Running tests
        run: bash ./gradlew test
