name: Android Pull Request to Release

on:
  pull_request:
    branches:
      - release-[0-9]+.[0-9]+.[0-9]+

jobs:
  test:
    name: Run Unit Tests
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip
          rm commandlinetools-linux-6858069_latest.zip
          mkdir -p vendor/cmdline-tools
          mv cmdline-tools vendor/cmdline-tools/
          mv vendor/cmdline-tools/cmdline-tools vendor/cmdline-tools/tools
          export PATH=$(pwd)/vendor/cmdline-tools/:$(pwd)/vendor/cmdline-tools/tools/bin:$PATH
          yes | sdkmanager "platforms;android-29"
          yes | sdkmanager "build-tools;28.0.3"
      - name: Read values
        id: package
        run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Running tests
        run: |
          export ANDROID_SDK_ROOT="$(pwd)/vendor"
          bash ./gradlew test --stacktrace
  
  apk:
    name: Generate APK
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip
          rm commandlinetools-linux-6858069_latest.zip
          mkdir -p vendor/cmdline-tools
          mv cmdline-tools vendor/cmdline-tools/
          mv vendor/cmdline-tools/cmdline-tools vendor/cmdline-tools/tools
          export PATH=$(pwd)/vendor/cmdline-tools/:$(pwd)/vendor/cmdline-tools/tools/bin:$PATH
          yes | sdkmanager "platforms;android-29"
          yes | sdkmanager "build-tools;28.0.3"
      - name: Read values
        id: package
        run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Build debug APK
        run:  |
          export ANDROID_SDK_ROOT="$(pwd)/vendor"
          bash ./gradlew assembleDebug
      - name: Upload APK to Github artfacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
